ALTER TABLE DEVUSER.BOARD
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEVUSER.BOARD CASCADE CONSTRAINTS;

CREATE TABLE DEVUSER.BOARD
(
  IDX         NUMBER(19)                        NOT NULL,
  TITLE       VARCHAR2(200 CHAR)                NOT NULL,
  CONTENTS    VARCHAR2(255 CHAR),
  AUTHOR      VARCHAR2(255 CHAR),
  CREATED_AT  VARCHAR2(100 CHAR)                NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE DEVUSER.MST_COM_CD_DETAIL_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEVUSER.MST_COM_CD_DETAIL_INFO CASCADE CONSTRAINTS;

CREATE TABLE DEVUSER.MST_COM_CD_DETAIL_INFO
(
  COM_CD_GRP_ID     VARCHAR2(20 BYTE)           NOT NULL,
  COM_CD_ID         VARCHAR2(20 BYTE)           NOT NULL,
  PARENT_COM_CD_ID  VARCHAR2(20 BYTE),
  COM_CD_NM         VARCHAR2(50 BYTE)           NOT NULL,
  COM_CD_NM_KR      VARCHAR2(50 BYTE)           NOT NULL,
  COM_CD_NM_JA      VARCHAR2(50 BYTE)           NOT NULL,
  COM_CD_DESC       VARCHAR2(255 BYTE)          NOT NULL,
  COM_CD_DESC_KR    VARCHAR2(255 BYTE)          NOT NULL,
  COM_CD_DESC_JA    VARCHAR2(255 BYTE)          NOT NULL,
  COM_CD_SORT_ORD   NUMBER(5)                   NOT NULL,
  COM_CD_USE_AT     CHAR(1 BYTE)                DEFAULT 'Y'                   NOT NULL,
  CREATED_USR_ID    VARCHAR2(32 BYTE)           NOT NULL,
  CREATED_DT        TIMESTAMP(6)                NOT NULL,
  UPDATED_USR_ID    VARCHAR2(32 BYTE)           NOT NULL,
  UPDATED_DT        TIMESTAMP(6)                NOT NULL,
  COM_CD_DIV1       VARCHAR2(20 BYTE),
  COM_CD_DIV2       VARCHAR2(20 BYTE),
  COM_CD_DIV3       VARCHAR2(20 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE DEVUSER.MST_COM_CD_DETAIL_INFO IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_DETAIL_INFO.COM_CD_GRP_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_DETAIL_INFO.COM_CD_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_DETAIL_INFO.PARENT_COM_CD_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_DETAIL_INFO.COM_CD_NM IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_DETAIL_INFO.COM_CD_NM_KR IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_DETAIL_INFO.COM_CD_NM_JA IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_DETAIL_INFO.COM_CD_DESC IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_DETAIL_INFO.COM_CD_DESC_KR IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_DETAIL_INFO.COM_CD_DESC_JA IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_DETAIL_INFO.COM_CD_SORT_ORD IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_DETAIL_INFO.COM_CD_USE_AT IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_DETAIL_INFO.CREATED_USR_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_DETAIL_INFO.CREATED_DT IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_DETAIL_INFO.UPDATED_USR_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_DETAIL_INFO.UPDATED_DT IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_DETAIL_INFO.COM_CD_DIV1 IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_DETAIL_INFO.COM_CD_DIV2 IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_DETAIL_INFO.COM_CD_DIV3 IS 'TRIAL';



ALTER TABLE DEVUSER.MST_COM_CD_GRP_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEVUSER.MST_COM_CD_GRP_INFO CASCADE CONSTRAINTS;

CREATE TABLE DEVUSER.MST_COM_CD_GRP_INFO
(
  COM_CD_GRP_ID        NVARCHAR2(20)            NOT NULL,
  COM_CD_GRP_NM        NVARCHAR2(30)            NOT NULL,
  COM_CD_GRP_NM_KR     NVARCHAR2(30)            NOT NULL,
  COM_CD_GRP_NM_JA     NVARCHAR2(30)            NOT NULL,
  COM_CD_GRP_DESC      NVARCHAR2(100)           NOT NULL,
  COM_CD_GRP_DESC_KR   NVARCHAR2(100)           NOT NULL,
  COM_CD_GRP_DESC_JA   NVARCHAR2(100)           NOT NULL,
  COM_CD_GRP_SORT_ORD  NUMBER(5)                NOT NULL,
  COM_CD_USE_AT        CHAR(1 BYTE)             DEFAULT 'Y'                   NOT NULL,
  CREATED_USR_ID       NVARCHAR2(32)            NOT NULL,
  CREATED_DT           TIMESTAMP(6)             NOT NULL,
  UPDATED_USR_ID       NVARCHAR2(32)            NOT NULL,
  UPDATED_DT           TIMESTAMP(6)             NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE DEVUSER.MST_COM_CD_GRP_INFO IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_GRP_INFO.COM_CD_GRP_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_GRP_INFO.COM_CD_GRP_NM IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_GRP_INFO.COM_CD_GRP_NM_KR IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_GRP_INFO.COM_CD_GRP_NM_JA IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_GRP_INFO.COM_CD_GRP_DESC IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_GRP_INFO.COM_CD_GRP_DESC_KR IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_GRP_INFO.COM_CD_GRP_DESC_JA IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_GRP_INFO.COM_CD_GRP_SORT_ORD IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_GRP_INFO.COM_CD_USE_AT IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_GRP_INFO.CREATED_USR_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_GRP_INFO.CREATED_DT IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_GRP_INFO.UPDATED_USR_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_COM_CD_GRP_INFO.UPDATED_DT IS 'TRIAL';



ALTER TABLE DEVUSER.MST_MENU_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEVUSER.MST_MENU_INFO CASCADE CONSTRAINTS;

CREATE TABLE DEVUSER.MST_MENU_INFO
(
  MENU_ID         NVARCHAR2(20)                 NOT NULL,
  MENU_NM         NVARCHAR2(50)                 NOT NULL,
  MENU_PARENT_ID  NVARCHAR2(20),
  SORT_ORD        NUMBER(5)                     NOT NULL,
  CREATED_USR_ID  NVARCHAR2(32)                 NOT NULL,
  CREATED_DT      TIMESTAMP(6)                  NOT NULL,
  UPDATED_USR_ID  NVARCHAR2(32)                 NOT NULL,
  UPDATED_DT      TIMESTAMP(6)                  NOT NULL,
  URL             NVARCHAR2(200),
  USE_YN          CHAR(1 BYTE)                  NOT NULL,
  TRIAL329        CHAR(1 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE DEVUSER.MST_MENU_INFO IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_MENU_INFO.MENU_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_MENU_INFO.MENU_NM IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_MENU_INFO.MENU_PARENT_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_MENU_INFO.SORT_ORD IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_MENU_INFO.CREATED_USR_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_MENU_INFO.CREATED_DT IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_MENU_INFO.UPDATED_USR_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_MENU_INFO.UPDATED_DT IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_MENU_INFO.URL IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_MENU_INFO.USE_YN IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_MENU_INFO.TRIAL329 IS 'TRIAL';



ALTER TABLE DEVUSER.MST_ROLE_MENU_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEVUSER.MST_ROLE_MENU_INFO CASCADE CONSTRAINTS;

CREATE TABLE DEVUSER.MST_ROLE_MENU_INFO
(
  ROLE_MENU_SEQ   NUMBER(38)                    NOT NULL,
  ROLE_READ       CHAR(1 BYTE),
  ROLE_CREATE     CHAR(1 BYTE),
  ROLE_UPDATE     CHAR(1 BYTE),
  ROLE_DELETE     CHAR(1 BYTE),
  ROLE_SEQ        NUMBER(38)                    NOT NULL,
  MENU_ID         NVARCHAR2(20)                 NOT NULL,
  CREATED_USR_ID  NVARCHAR2(32),
  CREATED_DT      TIMESTAMP(6),
  UPDATED_USR_ID  NVARCHAR2(32),
  UPDATED_DT      TIMESTAMP(6),
  USE_YN          CHAR(1 BYTE)                  NOT NULL,
  TRIAL335        CHAR(1 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE DEVUSER.MST_ROLE_MENU_INFO IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_ROLE_MENU_INFO.ROLE_MENU_SEQ IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_ROLE_MENU_INFO.ROLE_READ IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_ROLE_MENU_INFO.ROLE_CREATE IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_ROLE_MENU_INFO.ROLE_UPDATE IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_ROLE_MENU_INFO.ROLE_DELETE IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_ROLE_MENU_INFO.ROLE_SEQ IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_ROLE_MENU_INFO.MENU_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_ROLE_MENU_INFO.CREATED_USR_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_ROLE_MENU_INFO.CREATED_DT IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_ROLE_MENU_INFO.UPDATED_USR_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_ROLE_MENU_INFO.UPDATED_DT IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_ROLE_MENU_INFO.USE_YN IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_ROLE_MENU_INFO.TRIAL335 IS 'TRIAL';



ALTER TABLE DEVUSER.MST_SYS_SET_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEVUSER.MST_SYS_SET_INFO CASCADE CONSTRAINTS;

CREATE TABLE DEVUSER.MST_SYS_SET_INFO
(
  SYS_SET_ID      NUMBER(38)                    NOT NULL,
  SYS_SET_TYP     NVARCHAR2(50)                 NOT NULL,
  SYS_SET_NM      NVARCHAR2(50)                 NOT NULL,
  SYS_PARENT_ID   NVARCHAR2(50)                 NOT NULL,
  SYS_SET_DIV     NVARCHAR2(10)                 NOT NULL,
  SYS_SET_VAL     NVARCHAR2(255),
  CREATED_USR_ID  NVARCHAR2(32)                 NOT NULL,
  CREATED_DT      TIMESTAMP(6)                  NOT NULL,
  UPDATED_USR_ID  NVARCHAR2(32)                 NOT NULL,
  UPDATED_DT      TIMESTAMP(6)                  NOT NULL,
  TRIAL998        CHAR(1 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE DEVUSER.MST_SYS_SET_INFO IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_SYS_SET_INFO.SYS_SET_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_SYS_SET_INFO.SYS_SET_TYP IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_SYS_SET_INFO.SYS_SET_NM IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_SYS_SET_INFO.SYS_PARENT_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_SYS_SET_INFO.SYS_SET_DIV IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_SYS_SET_INFO.SYS_SET_VAL IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_SYS_SET_INFO.CREATED_USR_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_SYS_SET_INFO.CREATED_DT IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_SYS_SET_INFO.UPDATED_USR_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_SYS_SET_INFO.UPDATED_DT IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_SYS_SET_INFO.TRIAL998 IS 'TRIAL';



ALTER TABLE DEVUSER.MST_USR_AUTH_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEVUSER.MST_USR_AUTH_INFO CASCADE CONSTRAINTS;

CREATE TABLE DEVUSER.MST_USR_AUTH_INFO
(
  USR_AUTH_ID        NUMBER(38)                 NOT NULL,
  USR_TYPE           NUMBER(5)                  NOT NULL,
  USR_AUTH_ITEM_ID   VARCHAR2(10 BYTE)          NOT NULL,
  USR_AUTH_DISP_FLG  NUMBER(1)                  DEFAULT 0                     NOT NULL,
  USR_AUTH_ADD_FLG   NUMBER(1)                  DEFAULT 0                     NOT NULL,
  USR_AUTH_UPD_FLG   NUMBER(1)                  DEFAULT 0                     NOT NULL,
  USR_AUTH_DEL_FLG   NUMBER(1)                  DEFAULT 0                     NOT NULL,
  CREATE_DATETIME    TIMESTAMP(6)               NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE DEVUSER.MST_USR_AUTH_INFO IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_AUTH_INFO.USR_AUTH_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_AUTH_INFO.USR_TYPE IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_AUTH_INFO.USR_AUTH_ITEM_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_AUTH_INFO.USR_AUTH_DISP_FLG IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_AUTH_INFO.USR_AUTH_ADD_FLG IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_AUTH_INFO.USR_AUTH_UPD_FLG IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_AUTH_INFO.USR_AUTH_DEL_FLG IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_AUTH_INFO.CREATE_DATETIME IS 'TRIAL';



ALTER TABLE DEVUSER.MST_USR_CONN_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEVUSER.MST_USR_CONN_INFO CASCADE CONSTRAINTS;

CREATE TABLE DEVUSER.MST_USR_CONN_INFO
(
  CONN_ID         NUMBER(38)                    NOT NULL,
  USR_ID          VARCHAR2(32 BYTE)             NOT NULL,
  USR_SESSION_ID  VARCHAR2(100 BYTE),
  USR_ACT         VARCHAR2(20 BYTE)             NOT NULL,
  CREATED_DT      VARCHAR2(32 BYTE)             NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE DEVUSER.MST_USR_CONN_INFO IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_CONN_INFO.CONN_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_CONN_INFO.USR_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_CONN_INFO.USR_SESSION_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_CONN_INFO.USR_ACT IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_CONN_INFO.CREATED_DT IS 'TRIAL';



ALTER TABLE DEVUSER.MST_USR_GROUP_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEVUSER.MST_USR_GROUP_INFO CASCADE CONSTRAINTS;

CREATE TABLE DEVUSER.MST_USR_GROUP_INFO
(
  USR_GROUP_SEQ   NUMBER(38)                    NOT NULL,
  USR_GROUP_NM    VARCHAR2(50 BYTE)             NOT NULL,
  USR_GROUP_DESC  VARCHAR2(100 BYTE)            NOT NULL,
  CREATED_USR_ID  VARCHAR2(32 BYTE)             NOT NULL,
  CREATED_DT      TIMESTAMP(6)                  NOT NULL,
  UPDATED_USR_ID  VARCHAR2(32 BYTE)             NOT NULL,
  UPDATED_DT      TIMESTAMP(6)                  NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE DEVUSER.MST_USR_GROUP_INFO IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_GROUP_INFO.USR_GROUP_SEQ IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_GROUP_INFO.USR_GROUP_NM IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_GROUP_INFO.USR_GROUP_DESC IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_GROUP_INFO.CREATED_USR_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_GROUP_INFO.CREATED_DT IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_GROUP_INFO.UPDATED_USR_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_GROUP_INFO.UPDATED_DT IS 'TRIAL';



ALTER TABLE DEVUSER.MST_USR_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEVUSER.MST_USR_INFO CASCADE CONSTRAINTS;

CREATE TABLE DEVUSER.MST_USR_INFO
(
  USR_ID                VARCHAR2(32 BYTE)       NOT NULL,
  EMAIL                 VARCHAR2(50 BYTE)       NOT NULL,
  USR_NM                VARCHAR2(50 BYTE)       NOT NULL,
  USR_PWD               VARCHAR2(100 BYTE)      NOT NULL,
  USR_PWD_CREATED_DT    TIMESTAMP(6)            NOT NULL,
  USR_TEL               VARCHAR2(20 BYTE),
  MENU_ORD              VARCHAR2(250 BYTE)      NOT NULL,
  ROLE_SEQ              NUMBER(38),
  GROUP_SEQ             NUMBER(38),
  USR_LANG              VARCHAR2(2 BYTE),
  USR_IP                VARCHAR2(45 BYTE),
  LAST_NOTIFY_CLEAR_DT  TIMESTAMP(6),
  LAST_LOGIN_DT         TIMESTAMP(6),
  USE_YN                CHAR(1 BYTE),
  CREATED_DT            TIMESTAMP(6)            NOT NULL,
  UPDATED_USR_ID        VARCHAR2(32 BYTE)       NOT NULL,
  UPDATED_DT            TIMESTAMP(6)            NOT NULL,
  CREATED_USR_ID        VARCHAR2(32 BYTE)       NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE DEVUSER.MST_USR_INFO IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_INFO.USR_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_INFO.EMAIL IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_INFO.USR_NM IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_INFO.USR_PWD IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_INFO.USR_PWD_CREATED_DT IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_INFO.USR_TEL IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_INFO.MENU_ORD IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_INFO.ROLE_SEQ IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_INFO.GROUP_SEQ IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_INFO.USR_LANG IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_INFO.USR_IP IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_INFO.LAST_NOTIFY_CLEAR_DT IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_INFO.LAST_LOGIN_DT IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_INFO.USE_YN IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_INFO.CREATED_DT IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_INFO.UPDATED_USR_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_INFO.UPDATED_DT IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_INFO.CREATED_USR_ID IS 'TRIAL';



ALTER TABLE DEVUSER.MST_USR_ROLE_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEVUSER.MST_USR_ROLE_INFO CASCADE CONSTRAINTS;

CREATE TABLE DEVUSER.MST_USR_ROLE_INFO
(
  ROLE_SEQ        NUMBER(38)                    NOT NULL,
  ROLE_NM         VARCHAR2(50 BYTE)             NOT NULL,
  ROLE_DESC       VARCHAR2(100 BYTE)            NOT NULL,
  CREATED_USR_ID  VARCHAR2(32 BYTE)             NOT NULL,
  CREATED_DT      TIMESTAMP(6)                  NOT NULL,
  UPDATED_USR_ID  VARCHAR2(32 BYTE)             NOT NULL,
  UPDATED_DT      TIMESTAMP(6)                  NOT NULL,
  USE_YN          CHAR(1 BYTE)                  NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE DEVUSER.MST_USR_ROLE_INFO IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_ROLE_INFO.ROLE_SEQ IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_ROLE_INFO.ROLE_NM IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_ROLE_INFO.ROLE_DESC IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_ROLE_INFO.CREATED_USR_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_ROLE_INFO.CREATED_DT IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_ROLE_INFO.UPDATED_USR_ID IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_ROLE_INFO.UPDATED_DT IS 'TRIAL';

COMMENT ON COLUMN DEVUSER.MST_USR_ROLE_INFO.USE_YN IS 'TRIAL';



ALTER TABLE DEVUSER.USERS
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEVUSER.USERS CASCADE CONSTRAINTS;

CREATE TABLE DEVUSER.USERS
(
  ID          NUMBER(19)                        NOT NULL,
  EMAIL       VARCHAR2(200 CHAR)                NOT NULL,
  FIRST_NAME  VARCHAR2(255 CHAR),
  LAST_NAME   VARCHAR2(255 CHAR)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DEVUSER.MST_COM_CD_DETAIL_INFO_PKC ON DEVUSER.MST_COM_CD_DETAIL_INFO
(COM_CD_GRP_ID, COM_CD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX DEVUSER.MST_COM_CD_GRP_INFO_PKC ON DEVUSER.MST_COM_CD_GRP_INFO
(COM_CD_GRP_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX DEVUSER.MST_MENU_INFO_PKC ON DEVUSER.MST_MENU_INFO
(MENU_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX DEVUSER.MST_ROLE_MENU_INFO_PKC ON DEVUSER.MST_ROLE_MENU_INFO
(ROLE_MENU_SEQ)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX DEVUSER.MST_SYS_SET_INFO_PKC ON DEVUSER.MST_SYS_SET_INFO
(SYS_SET_ID, SYS_SET_TYP, SYS_SET_NM, SYS_PARENT_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX DEVUSER.MST_USR_AUTH_INFO_PKC ON DEVUSER.MST_USR_AUTH_INFO
(USR_AUTH_ID, USR_TYPE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX DEVUSER.MST_USR_CONN_INFO_PKC ON DEVUSER.MST_USR_CONN_INFO
(CONN_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX DEVUSER.MST_USR_GROUP_INFO_PKC ON DEVUSER.MST_USR_GROUP_INFO
(USR_GROUP_SEQ)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX DEVUSER.MST_USR_INFO_PKC ON DEVUSER.MST_USR_INFO
(USR_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX DEVUSER.MST_USR_ROLE_INFO_PKC ON DEVUSER.MST_USR_ROLE_INFO
(ROLE_SEQ)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


--  There is no statement for index DEVUSER.SYS_C007608.
--  The object is created when the parent object is created.

--  There is no statement for index DEVUSER.SYS_C007626.
--  The object is created when the parent object is created.

ALTER TABLE DEVUSER.BOARD ADD (
  PRIMARY KEY
  (IDX)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE DEVUSER.MST_COM_CD_DETAIL_INFO ADD (
  CONSTRAINT MST_COM_CD_DETAIL_INFO_PKC
  PRIMARY KEY
  (COM_CD_GRP_ID, COM_CD_ID)
  USING INDEX DEVUSER.MST_COM_CD_DETAIL_INFO_PKC
  ENABLE VALIDATE);

ALTER TABLE DEVUSER.MST_COM_CD_GRP_INFO ADD (
  CONSTRAINT MST_COM_CD_GRP_INFO_PKC
  PRIMARY KEY
  (COM_CD_GRP_ID)
  USING INDEX DEVUSER.MST_COM_CD_GRP_INFO_PKC
  ENABLE VALIDATE);

ALTER TABLE DEVUSER.MST_MENU_INFO ADD (
  CONSTRAINT MST_MENU_INFO_PKC
  PRIMARY KEY
  (MENU_ID)
  USING INDEX DEVUSER.MST_MENU_INFO_PKC
  ENABLE VALIDATE);

ALTER TABLE DEVUSER.MST_ROLE_MENU_INFO ADD (
  CONSTRAINT MST_ROLE_MENU_INFO_PKC
  PRIMARY KEY
  (ROLE_MENU_SEQ)
  USING INDEX DEVUSER.MST_ROLE_MENU_INFO_PKC
  ENABLE VALIDATE);

ALTER TABLE DEVUSER.MST_SYS_SET_INFO ADD (
  CONSTRAINT MST_SYS_SET_INFO_PKC
  PRIMARY KEY
  (SYS_SET_ID, SYS_SET_TYP, SYS_SET_NM, SYS_PARENT_ID)
  USING INDEX DEVUSER.MST_SYS_SET_INFO_PKC
  ENABLE VALIDATE);

ALTER TABLE DEVUSER.MST_USR_AUTH_INFO ADD (
  CONSTRAINT MST_USR_AUTH_INFO_PKC
  PRIMARY KEY
  (USR_AUTH_ID, USR_TYPE)
  USING INDEX DEVUSER.MST_USR_AUTH_INFO_PKC
  ENABLE VALIDATE);

ALTER TABLE DEVUSER.MST_USR_CONN_INFO ADD (
  CONSTRAINT MST_USR_CONN_INFO_PKC
  PRIMARY KEY
  (CONN_ID)
  USING INDEX DEVUSER.MST_USR_CONN_INFO_PKC
  ENABLE VALIDATE);

ALTER TABLE DEVUSER.MST_USR_GROUP_INFO ADD (
  CONSTRAINT MST_USR_GROUP_INFO_PKC
  PRIMARY KEY
  (USR_GROUP_SEQ)
  USING INDEX DEVUSER.MST_USR_GROUP_INFO_PKC
  ENABLE VALIDATE);

ALTER TABLE DEVUSER.MST_USR_INFO ADD (
  CONSTRAINT MST_USR_INFO_PKC
  PRIMARY KEY
  (USR_ID)
  USING INDEX DEVUSER.MST_USR_INFO_PKC
  ENABLE VALIDATE);

ALTER TABLE DEVUSER.MST_USR_ROLE_INFO ADD (
  CONSTRAINT MST_USR_ROLE_INFO_PKC
  PRIMARY KEY
  (ROLE_SEQ)
  USING INDEX DEVUSER.MST_USR_ROLE_INFO_PKC
  ENABLE VALIDATE);

ALTER TABLE DEVUSER.USERS ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ENABLE VALIDATE);
